version: '3.0'

services:
  react:
    container_name: react
    build: ./
    env_file:
      - .env.dev
    volumes:
      - '.:/var/frontend'
    ports:
      - '$REACT_PORT:10003'
    networks:
      - intra

networks:
  intra:
