version: '3.8'

services:
  react:
    container_name: react
    build: ./
    env_file:
      - .env.dev
    volumes:
      - '.:/var/frontend'
    ports:
      - "10003:10003"
    networks:
      - intra

networks:
  intra:
